version: "3.8"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: example
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  migration:
    image: golang:1.17
    working_dir: /work
    volumes:
      - .:/work:ro
    entrypoint: ["go", "run", "cmd/migration/main.go", "--dryrun=false", "--config", "environment/development/config.yml"]

  app:
    image: golang:1.17
    working_dir: /work
    volumes:
    - .:/work
    - ~/.config/gcloud:/gcloud:ro
    entrypoint: ["go", "run", "github.com/cosmtrek/air@latest", "-c", ".air.toml"]
    ports:
      - 8080:8080
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /gcloud/application_default_credentials.json

  trace:
    image: jaegertracing/all-in-one:1
    ports:
      - 127.0.0.1:16686:16686