version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: example
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  migration:
    build:
      context: .
    working_dir: /work
    volumes:
      - .:/work
    entrypoint: ["go", "run", "cmd/migration/main.go"]

  app:
    build:
      context: .
    working_dir: /work
    volumes:
    - .:/work
    command: ["make", "run"]
    ports:
      - 8080:8080

  trace:
    image: jaegertracing/all-in-one:1
    ports:
      - 127.0.0.1:16686:16686