openapi: 3.0.0
info:
  version: 1.0.0
  title: Example API
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  description: Example
  contact:
    name: Example
tags:
  - name: user
    description: user
servers:
  - url: 'http://localhost:8080'
paths:
  /tasks:
    post:
      requestBody:
        description: signin
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/task'
      responses:
        '200':
          description: response
  /my_tasks:
    get:
      responses:
        '200':
          description: response
  /signin:
    post:
      requestBody:
        description: signin
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/signin'
      responses:
        '200':
          description: response
  /signup:
    post:
      requestBody:
        description: signup
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/signup'
      responses:
        '200':
          description: response

components:
  schemas:
    task:
      type: object
      properties:
        title:
          type: string
      required:
        - title
    signin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    signup:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
      required:
        - email
        - password
        - name