db:
  user: root
  passwd:
  net: tcp
  host: db
  port: 3306
  db_name: example

trace:
  jaeger:
    url: http://trace:14268/api/traces
#  gcp:
#    project_id: your_gcp_project

logger:
  type: stdout