name: lint

on: ["push", "pull_request"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: build oapi
      run: make oapi-generate
    - name: get
      run: go get ./...
    - name: run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        args: --timeout 10m0s
